% Symbol Highlighting Patterns for NCL [NCAR COmmand Language]
%% for use with jed John E Davis slang editor
%% October 2012 TJ Olney added 6.1 keywords, resources, and functions
%% May  2011  TJ Olney  added 6.0 keywords, resources, and functions 
%  October 2008  TJ Olney 
%  June 2010  TJ Olney reworked to add resources and make sure keywords are recognized
%  Added the new functions and resources of 5.21 and fixed some
%  sorting order issues that prevented a few keywords with many
%  capital letters from being highlighted.
%  functions should appear as a different color than keywords 
%  and resources  If you want to add words of your own you must put
%  them in the lists in jed lexical order.  If in doubt, use the jed
%  sort function on the list.
%  There is a whitespace function invoked that will break pre 99.19
%  jed versions.  It can be safely commented out without affecting the
%  rest of the highlighting.
% To incorporate this in your jed environment, add the following to your
%   defaults.sl or to jed.rc (.jedrc)
%
%%  Mode_List_Exts +=
%%  ",ncl";
%%  Mode_List_Modes +=
%%  ",ncl";
%%    autoload ("ncl_mode", "ncl");
%%    add_mode_for_extension ("ncl", "ncl");
%%
%%
%%Then copy the ncl.sl file to the same place that your system stores
%%the rest of the .sl files.  $JED_ROOT/lib 
%% ------------------------------------------------------------------------------
%%
%% Highlighting Patterns for NCL for jed the slang editor
%% Patterns taken from the function and resource documentation at ncar  
%%
%% All reserved keywords are in the one  class, functions in another,
%% and ncl resources in a third.  TJ Olney
%% NCL functions from the alphabetical list plus the ncl reserved
%% Functions are in the 0 table.
%% Resources are in the 1 table.
%% keywords, class names, and some resource attribute allowed values  are in  the 2 table.
%% 
%% NCL contributed functions (2nd set)

$1 = "NCL";
create_syntax_table ($1);

%%define_highlight_rule ("[A-Za-z][A-Za-z0-9]*", "keyword3", $1);

define_syntax ("([{", ")]}", '(', $1);     	%  logical delimiters...'(' make these guys blink match
define_syntax ('"', '"', $1);			% string syntax from slang mode tjo
define_syntax( '\'', '\'', $1 );               % strings
define_syntax (";", "", '%', $1);   		%  semicolon starts a comment (from idl.sl)
define_syntax ("0-9a-zA-Z_", 'w', $1);        % words
define_syntax ("-+0-9a-fA-F.xX", '0', $1);   	% Numbers (just make them same color as comma
define_syntax ("$@.\,\.-+*/={}\:<>()[]|!&~^%", '+', $1); 		% operators  = '+'
define_syntax( '\\', '\\', $1 );               % escape character
set_syntax_flags ($1,0x2|0x4|0x40 );  % from Cmodet  set_syntax_flags ("NCL", 0x01| 0x2|0x4|0x40 );  case sensitive



%% table 0 is functions 
() = define_keywords_n ($1,  strcat(
"abs",
"all",
"any",
"avg",
"cos",
"csa",
"erf",
"exp",
"ind",
"log",
"max",
"min",
"mod",
"num",
"sin",
"sum",
"tan"), 3, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"acos",
"asin",
"atan",
"ceil",
"cosh",
"csa1",
"csa2",
"csa3",
"csad",
"csas",
"csax",
"draw",
"erfc",
"exit",
"fabs",
"gaus",
"mask",
"pdfx",
"rand",
"sinh",
"sqrt",
"tanh"), 4, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"atan2",
"cfftb",
"cfftf",
"clear",
"csa1d",
"csa1s",
"csa1x",
"csa2d",
"csa2l",
"csa2s",
"csa2x",
"csa3d",
"csa3l",
"csa3s",
"csa3x",
"csaxd",
"csaxs",
"csc2s",
"css2c",
"esacr",
"esacv",
"esccr",
"esccv",
"f2fsh",
"f2gsh",
"floor",
"frame",
"fspan",
"ft2db",
"ftest",
"g2fsh",
"g2gsh",
"gamma",
"gsn_y",
"hydro",
"int2p",
"isatt",
"isdim",
"isint",
"ispan",
"isvar",
"lapsF",
"lapsG",
"lapsf",
"lapsg",
"lapvf",
"lapvg",
"lclvl",
"log10",
"nnpnt",
"pdfxy",
"print",
"pslec",
"qsort",
"round",
"rtest",
"shaeC",
"shaec",
"shagC",
"shagc",
"shseC",
"shsec",
"shsgC",
"shsgc",
"sleep",
"smth9",
"srand",
"stat2",
"stat4",
"taper",
"toint",
"ttest",
"undef",
"vhaeC",
"vhaec",
"vhagC",
"vhagc",
"vhseC",
"vhsec",
"vhsgC",
"vhsgc",
"where"), 5, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"cancor",
"cdft_p",
"cdft_t",
"chiinv",
"csa1xd",
"csa1xs",
"csa2ld",
"csa2ls",
"csa2lx",
"csa2xd",
"csa2xs",
"csa3ld",
"csa3ls",
"csa3lx",
"csa3xd",
"csa3xs",
"csgetp",
"cssetp",
"csstri",
"csvoro",
"cumsum",
"cz2ccm",
"delete",
"dsgetp",
"dspnt2",
"dspnt3",
"dssetp",
"dtrend",
"dv2uvF",
"dv2uvG",
"dv2uvf",
"dv2uvg",
"eofcor",
"eofcov",
"eofunc",
"escorc",
"escovc",
"ezfftb",
"ezfftf",
"f2fosh",
"f2fshv",
"f2gshv",
"fft2db",
"fft2df",
"fo2fsh",
"ftcurv",
"ftgetp",
"ftkurv",
"ftsetp",
"ftsurf",
"g2fshv",
"g2gshv",
"getenv",
"gradsf",
"gradsg",
"gsn_xy",
"hlsrgb",
"hsvrgb",
"idsfft",
"ilapsF",
"ilapsG",
"ilapsf",
"ilapsg",
"ilapvf",
"ilapvg",
"isbyte",
"ischar",
"isfile",
"isfunc",
"islong",
"isproc",
"isuint",
"latGau",
"linint",
"linmsg",
"lspoly",
"maxind",
"minind",
"nggcog",
"nggetp",
"nglogo",
"ngsetp",
"nngetp",
"nnpntd",
"nnpnts",
"nnsetp",
"pslhor",
"pslhyp",
"relhum",
"rgbhls",
"rgbhsv",
"rgbyiq",
"runave",
"shgetp",
"shgrid",
"shsetp",
"simpeq",
"simpne",
"sizeof",
"spcorr",
"sqsort",
"stddev",
"strlen",
"svdcov",
"svdstd",
"system",
"tdclrs",
"tdctri",
"tdcudp",
"tdcurv",
"tddtri",
"tdez2d",
"tdez3d",
"tdgetp",
"tdgrds",
"tdgrid",
"tdgtrs",
"tdinit",
"tditri",
"tdlbla",
"tdlblp",
"tdlbls",
"tdline",
"tdlndp",
"tdlnpa",
"tdlpdp",
"tdmtri",
"tdotri",
"tdpara",
"tdplch",
"tdprpa",
"tdprpi",
"tdprpt",
"tdsetp",
"tdsort",
"tdstri",
"tdstrs",
"tdttri",
"tobyte",
"tochar",
"tolong",
"touint",
"typeof",
"update",
"uv2dvF",
"uv2dvG",
"uv2dvf",
"uv2dvg",
"uv2vrF",
"uv2vrG",
"uv2vrf",
"uv2vrg",
"vibeta",
"vr2uvF",
"vr2uvG",
"vr2uvf",
"vr2uvg",
"wmbarb",
"wmdrft",
"wmgetp",
"wmlabs",
"wmsetp",
"wmstnm",
"wmvect",
"wmvlbl",
"wrf_rh",
"wrf_td",
"wrf_tk",
"yiqrgb"), 6, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"ListPop",
"NewList",
"NhlDraw",
"NhlFree",
"NhlName",
"NhlOpen",
"addfile",
"betainc",
"bin_avg",
"bin_sum",
"boxplot",
"conform",
"copyatt",
"covcorm",
"crossp3",
"csa2lxd",
"csa2lxs",
"csa3lxd",
"csa3lxs",
"cssgrid",
"destroy",
"dim_avg",
"dim_max",
"dim_min",
"dim_num",
"dim_sum",
"dsgrid2",
"dsgrid3",
"dspnt2d",
"dspnt2s",
"dspnt3d",
"dspnt3s",
"echo_on",
"epsZero",
"f2foshv",
"fo2fshv",
"ftcurvd",
"ftcurvi",
"ftcurvp",
"ftcurvs",
"ftkurvd",
"ftkurvp",
"gsn_map",
"hsv2rgb",
"hyi2hyo",
"igradsF",
"igradsG",
"igradsf",
"igradsg",
"int2flt",
"int2p_n",
"iscoord",
"isfloat",
"isint64",
"isshort",
"isubyte",
"isulong",
"lderuvf",
"lderuvg",
"linint1",
"linint2",
"lonFlip",
"nameDim",
"natgrid",
"overlay",
"product",
"rdsstoi",
"regCoef",
"regcoef",
"regline",
"reshape",
"run_cor",
"shgetnp",
"sprintf",
"sprinti",
"taper_n",
"tofloat",
"toint64",
"toshort",
"toubyte",
"toulong",
"vinth2p",
"wavelet",
"wrf_avo",
"wrf_dbz",
"wrf_eth",
"wrf_map",
"wrf_pvo",
"wrf_slp",
"z2geouv"), 7, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"ListPush",
"NhlClose",
"NhlFrame",
"NhlGetBB",
"NhlIsApp",
"NhlRLGet",
"NhlRLSet",
"ShadeCOI",
"TJ_Olney",
"addfiles",
"byte2flt",
"cbinread",
"cdfbin_p",
"cdfbin_s",
"cdfchi_p",
"cdfchi_x",
"cdfgam_p",
"cdfgam_x",
"cdfnor_p",
"cdfnor_x",
"dble2flt",
"dim_rmsd",
"dimsizes",
"dsgrid2d",
"dsgrid2s",
"dsgrid3d",
"dsgrid3s",
"dtrend_n",
"echo_off",
"eof2data",
"fbinread",
"flt2dble",
"fluxEddy",
"ftcurvpi",
"ftcurvps",
"ftkurvpd",
"gammainc",
"gc_inout",
"gc_onarc",
"gc_qarea",
"gc_tarea",
"greg2jul",
"gsn_text",
"int2dble",
"isdouble",
"isstring",
"isuint64",
"isushort",
"jul2greg",
"linmsg_n",
"lonPivot",
"monthday",
"natgridd",
"natgrids",
"ndtooned",
"ngezlogo",
"nngetwts",
"nnpntend",
"onedtond",
"rho_mwjf",
"runave_n",
"sfvp2uvf",
"sfvp2uvg",
"spcorr_n",
"specx_ci",
"str_join",
"todouble",
"tosigned",
"tostring",
"touint64",
"toushort",
"trop_wmo",
"uv2sfvpF",
"uv2sfvpG",
"uv2sfvpf",
"uv2sfvpg",
"uv2vrdvF",
"uv2vrdvG",
"uv2vrdvf",
"uv2vrdvg",
"variance",
"vrdv2uvF",
"vrdv2uvG",
"vrdv2uvf",
"vrdv2uvg",
"zonalAve"), 8, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"ListCount",
"ListIndex",
"NhlCreate",
"NhlIsView",
"NhlMalloc",
"NhlNumber",
"NhlPError",
"PopLatLon",
"RGBtoCmap",
"add90LatX",
"add90LatY",
"asciiread",
"cbinwrite",
"cd_string",
"cdfbin_pr",
"cdfbin_xn",
"chartoint",
"clmDayTLL",
"clmMonLLT",
"clmMonTLL",
"datatondc",
"dim_avg_n",
"dim_gbits",
"dim_max_n",
"dim_min_n",
"dim_num_n",
"dim_spi_n",
"dim_stat4",
"dim_sum_n",
"dz_height",
"eofcor_ts",
"eofcov_ts",
"eofunc_ts",
"fbinwrite",
"gc_aangle",
"gc_dangle",
"gc_latlon",
"gc_pnt2gc",
"getDindex",
"gsn_csm_y",
"gsn_panel",
"gsn_table",
"inttobyte",
"inttochar",
"isdefined",
"isfilevar",
"isgraphic",
"isinteger",
"islogical",
"ismissing",
"isnumeric",
"kf_filter",
"latGauWgt",
"latGlobeF",
"latRegWgt",
"linint1_n",
"list_hlus",
"list_vars",
"local_max",
"local_min",
"lonGlobeF",
"longtoint",
"mjo_cross",
"ncargpath",
"ndctodata",
"nngetwtsd",
"nnpntendd",
"nnpntinit",
"omega_ccm",
"pdfxy_bin",
"pie_chart",
"plt_pdfxy",
"pop_remap",
"quadroots",
"rcm2rgrid",
"rgrid2rcm",
"short2flt",
"shsgc_R42",
"stat_trim",
"stdMonLLT",
"stdMonTLL",
"str_lower",
"str_match",
"str_split",
"str_strip",
"str_upper",
"str_write",
"student_t",
"svdcov_sv",
"svdstd_sv",
"tointeger",
"transpose",
"tri_trunC",
"tri_trunc",
"ut_string",
"uv2dv_cfd",
"uv2vr_cfd",
"v5d_close",
"v5d_write",
"wmbarbmap",
"wmvectmap",
"wrf_uvmet"), 9, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"NhlAddData",
"NhlDestroy",
"NhlRLClear",
"NhlRLIsSet",
"NhlRLUnSet",
"NhlRealloc",
"PopLatLonV",
"angmom_atm",
"asciiwrite",
"cd_convert",
"changeCase",
"chartolong",
"clmDayTLLL",
"clmMonLLLT",
"clmMonTLLL",
"dim_cumsum",
"dim_median",
"dim_pqsort",
"dim_rmsd_n",
"dim_rmvmed",
"dim_stddev",
"dtrend_msg",
"f2fsh_Wrap",
"f2gsh_Wrap",
"fbinnumrec",
"fileattdef",
"filedimdef",
"filegrpdef",
"filevardef",
"floattoint",
"flt2string",
"g2fsh_Wrap",
"g2gsh_Wrap",
"gaus_lobat",
"gc_clkwise",
"get1Dindex",
"getbitsone",
"getvaratts",
"getvardims",
"gsn_csm_xy",
"gsn_vector",
"int2p_Wrap",
"inttoshort",
"isdimnamed",
"isenumeric",
"isleapyear",
"isnan_ieee",
"issnumeric",
"isunsigned",
"latGlobeFo",
"latlon2utm",
"list_files",
"loadscript",
"lonGlobeFo",
"longtobyte",
"longtochar",
"mixhum_ptd",
"nnpntinitd",
"nnpntinits",
"pres_sigma",
"random_chi",
"rcm2points",
"region_ind",
"relhum_ttd",
"show_ascii",
"smth9_Wrap",
"specx_anal",
"stdMonLLLT",
"stdMonTLLL",
"str_concat",
"str_get_dq",
"str_get_nl",
"str_insert",
"str_switch",
"svd_lapack",
"systemfunc",
"tounsigned",
"ut_convert",
"utm2latlon",
"v5d_create",
"wgt_runave",
"wgt_volave",
"wrf_vector",
"zonal_mpsi"), 10, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"ESMF_regrid",
"ListGetType",
"ListSetType",
"NhlErrGetId",
"NhlGetGksCi",
"NhlNewColor",
"NhlRLCreate",
"NhlSetColor",
"cd_calendar",
"chartofloat",
"chartoshort",
"closest_val",
"day_of_week",
"day_of_year",
"dewtemp_trh",
"dim_avg_wgt",
"dim_product",
"dim_rmvmean",
"dim_stat4_n",
"dim_sum_wgt",
"doubletoint",
"drawNDCGrid",
"dv2uvF_Wrap",
"dv2uvG_Wrap",
"eof_varimax",
"eofcor_Wrap",
"eofcov_Wrap",
"eofunc_Wrap",
"exp_tapersh",
"f2fosh_Wrap",
"f2fshv_Wrap",
"f2gshv_Wrap",
"fbindirSwap",
"fbindirread",
"fbinrecread",
"fbinseqSwap",
"floattobyte",
"floattochar",
"floattolong",
"fo2fsh_Wrap",
"g2fshv_Wrap",
"g2gshv_Wrap",
"grid2triple",
"gsn_contour",
"gsn_csm_hov",
"gsn_csm_map",
"gsn_csm_x2y",
"gsn_csm_xy2",
"gsn_csm_xy3",
"gsn_polygon",
"ilapsF_Wrap",
"ilapsG_Wrap",
"ind_resolve",
"isMonotonic",
"isStrSubset",
"isbigendian",
"isunlimited",
"linrood_wgt",
"longtoshort",
"mixhum_ptrh",
"mjo_spectra",
"nngetsloped",
"nngetslopes",
"numAsciiCol",
"numAsciiRow",
"numeric2int",
"obj_anal_ic",
"pack_values",
"pattern_cor",
"prcwater_dp",
"pres2hybrid",
"printMinMax",
"print_table",
"reg_multlin",
"reshape_ind",
"rhomb_trunC",
"rhomb_trunc",
"rip_cape_2d",
"rip_cape_3d",
"rmAnnCycleD",
"rmInsufData",
"runave_Wrap",
"shorttobyte",
"shorttochar",
"sindex_yrmo",
"specxy_anal",
"stat_medrng",
"status_exit",
"str_capital",
"str_squeeze",
"str_sub_str",
"stringtoint",
"triple2grid",
"ushorttoint",
"ut_calendar",
"uv2dvF_Wrap",
"uv2dvG_Wrap",
"uv2vrF_Wrap",
"uv2vrG_Wrap",
"vr2uvF_Wrap",
"vr2uvG_Wrap",
"wgt_areaave",
"wgt_volrmse",
"wkSpaceTime",
"wrf_cape_2d",
"wrf_cape_3d",
"wrf_contour",
"wrf_overlay",
"wrf_times_c",
"write_table",
"yyyymm_time"), 11, 0);
 
 

 
() = define_keywords_n ($1,  strcat(
"GetFillColor",
"GetFillValue",
"NewCosWeight",
"NhlClassName",
"NhlDataToNDC",
"NhlErrGetMsg",
"NhlFreeColor",
"NhlGetValues",
"NhlNDCToData",
"NhlNewMarker",
"NhlRLDestroy",
"NhlSetMarker",
"NhlSetValues",
"attsetvalues",
"chartodouble",
"chartostring",
"conform_dims",
"copy_VarAtts",
"copy_VarMeta",
"cssgrid_Wrap",
"dim_avg_Wrap",
"dim_cumsum_n",
"dim_gamfit_n",
"dim_median_n",
"dim_numrun_n",
"dim_pqsort_n",
"dim_rmvmed_n",
"dim_stddev_n",
"dim_sum_Wrap",
"dim_variance",
"doubletobyte",
"doubletochar",
"doubletolong",
"dpres_plevel",
"dtrend_msg_n",
"eofcor_pcmsg",
"eofcov_pcmsg",
"exp_tapershC",
"f2foshv_Wrap",
"fbindirwrite",
"fbinrecwrite",
"fbinseqSwap1",
"fbinseqSwap2",
"flevarattdef",
"floattoshort",
"fo2fshv_Wrap",
"fourier_info",
"genCmapCnLvl",
"getFillValue",
"get_cpu_time",
"gsn_add_text",
"gsn_csm_x2y2",
"gsn_open_wks",
"gsn_polyline",
"gsn_text_ndc",
"hyi2hyo_Wrap",
"indStrSubset",
"int2p_n_Wrap",
"isfilevaratt",
"isfilevardim",
"kron_product",
"landsea_mask",
"linint1_Wrap",
"linint2_Wrap",
"local_max_1d",
"local_min_1d",
"natgrid_Wrap",
"ncargversion",
"niceLatLon2D",
"nngetaspectd",
"nngetaspects",
"oneDtostring",
"printVarInfo",
"random_gamma",
"rmAnnCycle1D",
"sigma2hybrid",
"snindex_yrmo",
"solve_linsys",
"str_get_cols",
"str_is_blank",
"str_match_ic",
"stringtochar",
"stringtolong",
"symMinMaxPlt",
"v5d_setUnits",
"wgt_areaave2",
"wgt_arearmse",
"wgt_areasum2",
"wgt_runave_n",
"wk_smooth121",
"wrf_helicity",
"wrf_ij_to_ll",
"wrf_ll_to_ij",
"wrf_map_zoom",
"wrf_mapres_c",
"wrf_overlays",
"write_matrix"),12,  0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"NhlAddOverlay",
"NhlErrNumMsgs",
"NhlInitialize",
"NhlIsDataComm",
"NhlIsDataItem",
"NhlIsDataSpec",
"NhlNDCPolygon",
"NhlRLGetArray",
"NhlRLGetFloat",
"NhlRLSetArray",
"NhlRLSetFloat",
"NhlRemoveData",
"NhlUpdateData",
"SqrtCosWeight",
"WindRoseBasic",
"WindRoseColor",
"area_hi2lores",
"chartointeger",
"clmMon2clmDay",
"craybinnumrec",
"days_in_month",
"decimalPlaces",
"depth_to_pres",
"dim_avg_wgt_n",
"dim_product_n",
"dim_rmsd_Wrap",
"dim_rmvmean_n",
"dim_sum_wgt_n",
"doubletofloat",
"doubletoshort",
"filevarattdef",
"genNormalDist",
"gsn_histogram",
"infoTimeStamp",
"integertobyte",
"integertochar",
"isfilepresent",
"list_filevars",
"longtointeger",
"moc_globe_atl",
"msgValOutline",
"paleo_outline",
"random_normal",
"readAsciiHead",
"runave_n_Wrap",
"setfileoption",
"short2flt_hdf",
"smthClmDayTLL",
"str_get_field",
"str_match_ind",
"str_split_csv",
"stringtofloat",
"stringtoshort",
"triple2grid2d",
"unique_string",
"v5d_setLowLev",
"v5d_write_var",
"vinth2p_ecmwf",
"vinth2p_nodes",
"vintp2p_ecmwf",
"wgt_arearmse2",
"wrf_interp_1d",
"wrf_smooth_2d",
"yyyymmdd_time"), 13, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"NhlDataPolygon",
"NhlErrAddTable",
"NhlGetParentId",
"NhlIsTransform",
"NhlNDCPolyline",
"NhlRLGetDouble",
"NhlRLGetString",
"NhlRLSetDouble",
"NhlRLSetString",
"ShadeGtContour",
"ShadeLtContour",
"calcDayAnomTLL",
"calcMonAnomLLT",
"calcMonAnomTLL",
"changeCaseChar",
"copy_VarCoords",
"craybinrecread",
"delete_VarAtts",
"dim_avg_n_Wrap",
"dim_max_n_Wrap",
"dim_min_n_Wrap",
"dim_sum_n_Wrap",
"dim_variance_n",
"dtrend_leftdim",
"eofunc_ts_Wrap",
"eofunc_varimax",
"filwgts_lancos",
"filwgts_normal",
"floattointeger",
"gaus_lobat_wgt",
"getVarDimNames",
"getfilevaratts",
"getfilevardims",
"gsn_blank_plot",
"gsn_csm_map_ce",
"gsn_csm_vector",
"gsn_legend_ndc",
"gsn_polymarker",
"gsn_streamline",
"gsn_vector_map",
"integertoshort",
"inverse_matrix",
"isfilevarcoord",
"linint1_n_Wrap",
"linint2_points",
"linrood_latwgt",
"list_procfuncs",
"mjo_cross_plot",
"namedcolor2rgb",
"nice_mnmxintvl",
"random_uniform",
"rcm2rgrid_Wrap",
"readAsciiTable",
"remap_elements",
"rgrid2rcm_Wrap",
"rmMonAnnCycLLT",
"rmMonAnnCycTLL",
"rm_single_dims",
"shsgc_R42_Wrap",
"skewT_PlotData",
"stdatmus_p2tdz",
"stdatmus_z2tdp",
"str_left_strip",
"stringtodouble",
"wgt_volave_ccm",
"wind_component",
"wind_direction"), 14, 0);
 
 
 
 
() = define_keywords_n ($1,  strcat(
"NhlAddPrimitive",
"NhlDataPolyline",
"NhlErrClearMsgs",
"NhlErrFPrintMsg",
"NhlErrSPrintMsg",
"NhlRLGetInteger",
"NhlRLGetMDArray",
"NhlRLSetInteger",
"NhlRLSetMDArray",
"NormCosWgtGlobe",
"addfiles_GetVar",
"assignFillValue",
"calcMonAnomLLLT",
"calcMonAnomTLLL",
"cd_inv_calendar",
"charactertolong",
"cshstringtolist",
"dim_cumsum_Wrap",
"dim_rmsd_n_Wrap",
"dim_rmvmed_Wrap",
"dim_standardize",
"dim_stddev_Wrap",
"doubletointeger",
"filechunkdimdef",
"filevarchunkdef",
"filevardimsizes",
"filwgts_lanczos",
"getVarFillValue",
"get_file_suffix",
"get_ncl_version",
"get_script_name",
"getfiledimsizes",
"getfilegrpnames",
"getfilevarnames",
"getfilevartypes",
"getind_latlon2d",
"gsn_add_polygon",
"gsn_contour_map",
"gsn_coordinates",
"gsn_create_text",
"gsn_csm_contour",
"gsn_polygon_ndc",
"latlon_to_SCRIP",
"longtocharacter",
"maximize_output",
"month_to_annual",
"month_to_season",
"pres_hybrid_ccm",
"printVarSummary",
"rcm2points_Wrap",
"replace_ieeenan",
"rmMonAnnCycLLLT",
"stat_dispersion",
"str_right_strip",
"stringtointeger",
"time_to_newtime",
"ut_inv_calendar",
"wave_number_spc",
"wavelet_default",
"wgt_area_smooth",
"wgt_runave_Wrap",
"wgt_volrmse_ccm",
"wkSpaceTime_cam",
"wrf_interp_3d_z",
"wrf_map_overlay",
"wrf_user_getvar",
"zonal_mpsi_Wrap"), 15, 0);
 
() = define_keywords_n ($1,  strcat(
"NhlAddAnnotation",
"NhlIsWorkstation",
"NhlNDCPolymarker",
"NhlPalGetDefined",
"NhlRemoveOverlay",
"ShadeGeLeContour",
"ShadeLtGtContour",
"calendar_decode2",
"charactertofloat",
"charactertoshort",
"copy_VarCoords_1",
"copy_VarCoords_2",
"decomposeSymAsym",
"dim_avg_wgt_Wrap",
"dim_rmvmean_Wrap",
"dim_sum_wgt_Wrap",
"dpres_hybrid_ccm",
"dtrend_quadratic",
"exp_tapersh_wgts",
"floattocharacter",
"grib_stime2itime",
"gsn_add_polyline",
"gsn_attach_plots",
"gsn_csm_lat_time",
"gsn_csm_pres_hgt",
"gsn_csm_time_lat",
"gsn_labelbar_ndc",
"gsn_polyline_ndc",
"merge_levels_sfc",
"month_to_seasonN",
"obj_anal_ic_Wrap",
"omega_ccm_driver",
"potmp_insitu_ocn",
"pres2hybrid_Wrap",
"shorttocharacter",
"skewT_BackGround",
"str_fields_count",
"str_match_ind_ic",
"time_axis_labels",
"triple2grid_Wrap",
"wgt_areaave_Wrap",
"wrf_interp_2d_xy",
"wrf_latlon_to_ij",
"wrf_map_overlays",
"wrf_user_intrp2d",
"wrf_user_intrp3d"), 16, 0);
 
() = define_keywords_n ($1,  strcat(
"GetFillColorIndex",
"NhlDataPolymarker",
"NhlNewDashPattern",
"NhlSetDashPattern",
"WindRoseThickLine",
"cfftf_frq_reorder",
"charactertodouble",
"charactertostring",
"default_fillvalue",
"dim_cumsum_n_Wrap",
"dim_rmvmed_n_Wrap",
"dim_standardize_n",
"dim_stddev_n_Wrap",
"dim_variance_Wrap",
"doubletocharacter",
"dpres_plevel_Wrap",
"equiv_sample_size",
"generate_2d_array",
"get_sphere_radius",
"gsn_contour_shade",
"gsn_create_legend",
"gsn_csm_map_polar",
"gsn_draw_colormap",
"gsn_vector_scalar",
"ind_nearest_coord",
"mixed_layer_depth",
"mjo_cross_coh2pha",
"mjo_cross_segment",
"mjo_xcor_lag_ovly",
"month_to_season12",
"poisson_grid_fill",
"random_setallseed",
"replaceSingleChar",
"set_sphere_radius",
"span_named_colors",
"stringtocharacter",
"table_attach_rows",
"wgt_runave_n_Wrap",
"wgt_vert_avg_beta",
"wrf_map_resources",
"wrf_user_ij_to_ll",
"wrf_user_ll_to_ij"), 17, 0);

() = define_keywords_n ($1,  strcat(
"NhlRLGetFloatArray",
"NhlRLSetFloatArray",
"NhlRemovePrimitive",
"area_hi2lores_Wrap",
"center_finite_diff",
"charactertointeger",
"dim_avg_wgt_n_Wrap",
"dim_rmvmean_n_Wrap",
"dim_sum_wgt_n_Wrap",
"get1Dindex_Exclude",
"getfilevardimsizes",
"gsn_add_annotation",
"gsn_add_polymarker",
"gsn_csm_blank_plot",
"gsn_csm_streamline",
"gsn_csm_vector_map",
"gsn_polymarker_ndc",
"gsn_streamline_map",
"integertocharacter",
"mjo_spectra_season",
"read_colormap_file",
"sparse_matrix_mult",
"wgt_runave_leftdim",
"wrf_user_unstagger",
"yyyymm_to_yyyyfrac"), 18, 0);
 
() = define_keywords_n ($1,  strcat(
"NhlClearWorkstation",
"NhlGetErrorObjectId",
"NhlIsAllocatedColor",
"NhlRLGetDoubleArray",
"NhlRLGetStringArray",
"NhlRLSetDoubleArray",
"NhlRLSetStringArray",
"NhlRemoveAnnotation",
"area_conserve_remap",
"array_append_record",
"band_pass_area_time",
"dim_variance_n_Wrap",
"eofunc_varimax_Wrap",
"get1Dindex_Collapse",
"gsn_create_labelbar",
"gsn_csm_contour_map",
"gsn_define_colormap",
"gsn_merge_colormaps",
"linint2_points_Wrap",
"mjo_xcor_lag_season",
"printFileVarSummary",
"resolveWavesHayashi",
"str_index_of_substr",
"str_split_by_length",
"vinth2p_ecmwf_nodes",
"wallClockElapseTime",
"wrf_user_list_times",
"yyyyddd_to_yyyymmdd",
"yyyymmdd_to_yyyyddd"), 19, 0);
 
() = define_keywords_n ($1,  strcat(
"NhlChangeWorkstation",
"NhlGetClassResources",
"NhlRLGetIntegerArray",
"NhlRLGetMDFloatArray",
"NhlRLSetIntegerArray",
"NhlRLSetMDFloatArray",
"NhlUpdateWorkstation",
"band_pass_hovmueller",
"center_finite_diff_n",
"curvilinear_to_SCRIP",
"dim_standardize_Wrap",
"gsn_reverse_colormap",
"mjo_phase_background",
"mjo_space_time_cross",
"rectilinear_to_SCRIP",
"setColorContourClear",
"table_attach_columns",
"unstructured_to_ESMF",
"wrf_updraft_helicity",
"yyyymmdd_to_yyyyfrac"), 20, 0);
 
() = define_keywords_n ($1,  strcat(
"NhlGetNamedColorIndex",
"NhlRLGetMDDoubleArray",
"NhlRLSetMDDoubleArray",
"band_pass_latlon_time",
"gsn_csm_vector_map_ce",
"gsn_csm_vector_scalar",
"gsn_draw_named_colors",
"gsn_retrieve_colormap",
"gsn_streamline_scalar",
"gsn_vector_scalar_map",
"set_default_fillvalue",
"wrf_user_latlon_to_ij"), 21, 0);

() = define_keywords_n ($1,  strcat(
"NhlRLGetMDIntegerArray",
"NhlRLSetMDIntegerArray",
"dim_standardize_n_Wrap",
"dtrend_quadratic_msg_n",
"eofunc_varimax_reorder",
"get_script_prefix_name",
"gsn_csm_contour_map_ce",
"gsn_csm_streamline_map",
"yyyymmddhh_to_yyyyfrac"), 22, 0);
 
() = define_keywords_n ($1,  strcat(
"ESMF_regrid_gen_weights",
"NhlGetParentWorkstation",
"NhlGetWorkspaceObjectId",
"filevarcompressleveldef",
"generate_unique_indices",
"gsn_csm_pres_hgt_vector",
"mjo_wavenum_freq_season",
"mjo_xcor_lag_ovly_panel"), 23, 0);
 
() = define_keywords_n ($1,  strcat(
"ESMF_regrid_with_weights",
"NhlAppGetDefaultParentId",
"area_conserve_remap_Wrap",
"band_pass_area_time_plot",
"gsn_csm_vector_map_polar",
"month_to_annual_weighted",
"reset_device_coordinates"), 24, 0);
 
() = define_keywords_n ($1,  strcat(
"band_pass_hovmueller_plot",
"gsn_csm_contour_map_polar",
"gsn_csm_streamline_map_ce",
"gsn_csm_vector_scalar_map",
"gsn_streamline_scalar_map"), 25, 0);

() = define_keywords_n ($1,  strcat(
"ColorNegDashZeroPosContour",
"band_pass_latlon_time_plot",
"gsn_add_shapefile_polygons",
"gsn_csm_attach_zonal_means"), 26, 0);
 
() = define_keywords_n ($1,  strcat(
"gsn_add_shapefile_polylines",
"gsn_csm_contour_map_overlay",
"gsn_csm_pres_hgt_streamline",
"monthly_total_to_daily_mean"), 27, 0);
 
() = define_keywords_n ($1,  strcat(
"gsn_csm_streamline_map_polar",
"gsn_csm_vector_scalar_map_ce",
"mjo_wavenum_freq_season_plot"), 28, 0);

() = define_keywords_n ($1,  strcat(
"gsn_add_shapefile_polymarkers"), 29, 0);

 
() = define_keywords_n ($1, "gsn_csm_streamline_contour_map", 30, 0);
 
() = define_keywords_n ($1, "gsn_csm_vector_scalar_map_polar", 31, 0);
 
() = define_keywords_n ($1, "gsn_csm_streamline_contour_map_ce", 33, 0);
 
() = define_keywords_n ($1, "gsn_csm_streamline_contour_map_polar",36, 0); 
 
%%%%%%%%%%%%%%%%%%%%%%%% end of functions and keywords %%%%%%%%%5
%%%%%%%%%%%%%%%%%%%%%%%% 
%%%%%%%%%%%%%%%%%%%%%%%%   
%%% table 1 is resources  length 2 and 3 are resource prefixes only
%%% may not have legitimate use alone.
() = define_keywords_n ($1, "amcacnctdcgslblgmppmprsfsttftitmtrtxvcvfvpwkwsxy", 2, 1);

() = define_keywords_n ($1, strcat(
"app",
"err",
"gsn"), 3, 1);

() = define_keywords_n ($1, strcat(
 "amOn",
"vpOn",
"vpXF",
"vpYF"), 4, 1);

() = define_keywords_n ($1, strcat(
 "amJust",
"amSide",
"amZone",
"cnFill",
"gsFont",
"tmXBOn",
"tmXTOn",
"tmYLOn",
"tmYROn",
"trXLog",
"trYLog",
"txFont",
"txJust"), 6, 1);

() = define_keywords_n ($1,  strcat ( 
"caXCast",
"caXMaxV",
"caXMinV",
"caYCast",
"caYMaxV",
"caYMinV",
"ctXMaxV",
"ctXMinV",
"ctYMaxV",
"ctYMinV",
"gsnDraw",
"trXMaxF",
"trXMinF",
"trYMaxF",
"trYMinF",
"txPosXF",
"txPosYF",
"vfUMaxV",
"vfUMinV",
"vfVMaxV",
"vfVMinV",
"wkPause",
"wkViews",
"wkWidth"), 7 , 1);

() = define_keywords_n ($1, strcat(

"amDataXF",
"amDataYF",
"amViewId",
"caXArray",
"caYArray",
"cnFillOn",
"cnLevels",
"ctXTable",
"ctYTable",
"errLevel",
"errPrint",
"gsClipOn",
"gsnFrame",
"gsnPolar",
"gsnScale",
"gsnShape",
"mpFillOn",
"prXArray",
"prYArray",
"sfXArray",
"sfXCEndV",
"sfYArray",
"sfYCEndV",
"stLevels",
"tiDeltaF",
"tiMainOn",
"tmXBMode",
"tmXTMode",
"tmYLMode",
"tmYRMode",
"txAngleF",
"txString",
"vcLevels",
"vfXArray",
"vfXCEndV",
"vfYArray",
"vfYCEndV",
"vpClipOn",
"vpWidthF",
"wkHeight",
"xyMarker",
"xyXStyle",
"xyYStyle"), 8, 1);

() = define_keywords_n ($1, strcat(
"appSysDir",
"appUsrDir",
"cnLinesOn",
"errBuffer",
"gsEdgesOn",
"lbPerimOn",
"lbTitleOn",
"lgPerimOn",
"lgTitleOn",
"mpMaxLatF",
"mpMaxLonF",
"mpMinLatF",
"mpMinLonF",
"mpPerimOn",
"mpTopNDCF",
"mpTopNPCF",
"tiXAxisOn",
"tiYAxisOn",
"tmXBStyle",
"tmXTStyle",
"tmYLStyle",
"tmYRStyle",
"txPerimOn",
"vfMagMaxV",
"vfMagMinV",
"vpHeightF",
"xyMarkers"), 9 , 1);


() = define_keywords_n ($1,  strcat(
"cnFillMode",
"errFilePtr",
"gsnPanelXF",
"gsnPanelYF",
"gsnPolarUT",
"lbBoxCount",
"lbLabelsOn",
"lgItemType",
"lgLabelsOn",
"lgLegendOn",
"mpLabelsOn",
"mpLeftNDCF",
"mpLeftNPCF",
"prPolyType",
"sfCopyData",
"sfDataMaxV",
"sfDataMinV",
"sfXCStartV",
"sfXCStride",
"sfYCStartV",
"sfYCStride",
"tiMainFont",
"tiMainJust",
"tiMainSide",
"tmXBFormat",
"tmXBLabels",
"tmXBValues",
"tmXTFormat",
"tmXTLabels",
"tmXTValues",
"tmYLFormat",
"tmYLLabels",
"tmYLValues",
"tmYRFormat",
"tmYRLabels",
"tmYRValues",
"tmYUseLeft",
"trGridType",
"trXReverse",
"trXSamples",
"trYReverse",
"trYSamples",
"txFuncCode",
"vcLabelsOn",
"vfCopyData",
"vfGridType",
"vfXCStartV",
"vfXCStride",
"vfYCStartV",
"vfYCStride",
"wkColorMap",
"wkFileName",
"wkMetaName",
"wkPSFormat",
"wkWindowId"), 10 , 1);


() = define_keywords_n ($1, strcat(
 "amTrackData",
"caXMissingV",
"caYMissingV",
"cnFillColor",
"cnLevelFlag",
"cnLineColor",
"ctXMissingV",
"ctYMissingV",
"errFileName",
"gsEdgeColor",
"gsFillColor",
"gsFillIndex",
"gsFontColor",
"gsLineColor",
"gsnMaximize",
"gsnPanelTop",
"gsnXRefLine",
"gsnYRefLine",
"lbBoxSizing",
"lbFillColor",
"lbLabelFont",
"lbLabelJust",
"lbPerimFill",
"lbTitleFont",
"lbTitleJust",
"lgDashIndex",
"lgItemCount",
"lgItemOrder",
"lgItemTypes",
"lgLabelFont",
"lgLabelJust",
"lgLineColor",
"lgPerimFill",
"lgTitleFont",
"lgTitleJust",
"mpAreaNames",
"mpAreaTypes",
"mpFillColor",
"mpLimitMode",
"mpOutlineOn",
"mpRightNDCF",
"mpRightNPCF",
"mpShapeMode",
"mpTopAngleF",
"pmAnnoViews",
"pmTitleZone",
"sfDataArray",
"stLineColor",
"stStepSizeF",
"tiXAxisFont",
"tiXAxisJust",
"tiXAxisSide",
"tiYAxisFont",
"tiYAxisJust",
"tiYAxisSide",
"tmXBMinorOn",
"tmXTMinorOn",
"tmYLMinorOn",
"tmYRMinorOn",
"trXAxisType",
"trXTensionF",
"trYAxisType",
"trYTensionF",
"txDirection",
"txFontColor",
"vcMinAnnoOn",
"vcRefAnnoOn",
"vfDataArray",
"vfPolarData",
"wkGksWorkId",
"wkPDFFormat",
"wkPaperSize",
"xyCoordData",
"xyLabelMode",
"xyLineColor") , 11 , 1);


() = define_keywords_n ($1, strcat( 
"appResources",
"caCopyArrays",
"cnFillColors",
"cnFillScaleF",
"cnFillScales",
"cnLevelCount",
"cnLevelFlags",
"cnLineColors",
"ctCopyTables",
"ctXTableType",
"ctYTableType",
"gsFillScaleF",
"gsTextAngleF",
"gsnAddCyclic",
"gsnBoxMargin",
"gsnPanelLeft",
"gsnPolarTime",
"gsnZonalMean",
"lbAutoManage",
"lbBoxLinesOn",
"lbFillColors",
"lbFillScaleF",
"lbFillScales",
"lbLabelBarOn",
"lbPerimColor",
"lbTopMarginF",
"lgAutoManage",
"lgBoxLinesOn",
"lgLineColors",
"lgPerimColor",
"lgTopMarginF",
"mpBottomNDCF",
"mpBottomNPCF",
"mpCenterLatF",
"mpCenterLonF",
"mpCenterRotF",
"mpFillColors",
"mpFillScaleF",
"mpFillScales",
"mpLeftAngleF",
"mpProjection",
"mpTopMapPosF",
"mpTopWindowF",
"pmLegendSide",
"pmLegendZone",
"sfXCEndIndex",
"sfYCEndIndex",
"stLevelCount",
"tiMainAngleF",
"tiMainString",
"tmXBBorderOn",
"tmXBLabelsOn",
"tmXBMaxTicks",
"tmXBTickEndF",
"tmXMajorGrid",
"tmXMinorGrid",
"tmXTBorderOn",
"tmXTLabelsOn",
"tmXTMaxTicks",
"tmXTTickEndF",
"tmXUseBottom",
"tmYLBorderOn",
"tmYLDataTopF",
"tmYLLabelsOn",
"tmYLMaxTicks",
"tmYLTickEndF",
"tmYMajorGrid",
"tmYMinorGrid",
"tmYRBorderOn",
"tmYRDataTopF",
"tmYRLabelsOn",
"tmYRMaxTicks",
"tmYRTickEndF",
"txPerimColor",
"vcGlyphStyle",
"vcLevelCount",
"vcRefLengthF",
"vfUDataArray",
"vfVDataArray",
"vfXCEndIndex",
"vfYCEndIndex",
"vpKeepAspect",
"wkColorModel",
"wkPSFileName",
"wkVisualType",
"wkXColorMode",
"xyLineColors",
"xyMonoMarker"), 12 , 1);


() = define_keywords_n ($1, strcat( 
"appFileSuffix",
"cnFillPalette",
"cnFillPattern",
"cnInfoLabelOn",
"cnLinePalette",
"cnLowLabelsOn",
"cnSmoothingOn",
"errUnitNumber",
"gsFontAspectF",
"gsFontHeightF",
"gsFontQuality",
"gsMarkerColor",
"gsMarkerIndex",
"gsMarkerSizeF",
"gsnLeftString",
"gsnPanelDebug",
"gsnPanelRight",
"gsnPaperWidth",
"gsnStringFont",
"gsnXYBarChart",
"lbFillPattern",
"lbLabelAngleF",
"lbLabelStride",
"lbLeftMarginF",
"lbOrientation",
"lbTitleAngleF",
"lbTitleString",
"lgDashIndexes",
"lgLabelAngleF",
"lgLabelStride",
"lgLeftMarginF",
"lgMarkerColor",
"lgMarkerIndex",
"lgMarkerSizeF",
"lgMarkerSizes",
"lgOrientation",
"lgTitleAngleF",
"lgTitleString",
"mpDataMaxLonF",
"mpDataMinLonF",
"mpDataSetName",
"mpFillPattern",
"mpGridMaxLatF",
"mpLeftMapPosF",
"mpLeftWindowF",
"mpRightAngleF",
"sfXCellBounds",
"sfYCellBounds",
"stArrowStride",
"stLabelFormat",
"stLevelColors",
"tiXAxisAngleF",
"tiXAxisString",
"tiYAxisAngleF",
"tiYAxisString",
"tmXBDataLeftF",
"tmXBLabelFont",
"tmXBLabelJust",
"tmXBPrecision",
"tmXTDataLeftF",
"tmXTLabelFont",
"tmXTLabelJust",
"tmXTPrecision",
"tmYLLabelFont",
"tmYLLabelJust",
"tmYLPrecision",
"tmYRLabelFont",
"tmYRLabelJust",
"tmYRPrecision",
"txFontAspectF",
"txFontHeightF",
"txFontQuality",
"txPerimSpaceF",
"vcLevelColors",
"vcMinAnnoFont",
"vcMinAnnoJust",
"vcMinAnnoSide",
"vcMinAnnoZone",
"vcRefAnnoFont",
"vcRefAnnoJust",
"vcRefAnnoSide",
"vcRefAnnoZone",
"vpUseSegments",
"wkColorMapLen",
"wkOrientation",
"wkPDFFileName",
"wkPaperWidthF",
"wsCurrentSize",
"wsMaximumSize",
"xyComputeXMax",
"xyComputeXMin",
"xyComputeYMax",
"xyComputeYMin",
"xyDashPattern",
"xyMarkerColor",
"xyMarkerSizeF",
"xyMarkerSizes"),13,1); 


				    
() = define_keywords_n ($1, strcat( 
"amParallelPosF",
"amResizeNotify",
"cnFillDotSizeF",
"cnFillOpacityF",
"cnFillPatterns",
"cnFixFillBleed",
"cnHighLabelsOn",
"cnLabelMasking",
"cnLineLabelsOn",
"cnLowLabelFont",
"cnMaxLevelValF",
"cnMinLevelValF",
"cnRasterModeOn",
"ctXElementSize",
"ctYElementSize",
"dcDelayCompute",
"gsFillDotSizeF",
"gsFillOpacityF",
"gsFontOpacityF",
"gsLineOpacityF",
"gsTextFuncCode",
"gsnPanelBottom",
"gsnPanelCenter",
"gsnPaperHeight",
"gsnPaperMargin",
"gsnRightString",
"gsnTickMarksOn",
"lbBoxFractions",
"lbBoxLineColor",
"lbFillDotSizeF",
"lbFillPatterns",
"lbLabelOffsetF",
"lbLabelStrings",
"lbMaxLabelLenF",
"lbRasterFillOn",
"lbRightMarginF",
"lbTitleExtentF",
"lbTitleOffsetF",
"lgBoxLineColor",
"lgLabelOffsetF",
"lgLabelStrings",
"lgLineLabelsOn",
"lgMarkerColors",
"lgMonoItemType",
"lgRightMarginF",
"lgTitleExtentF",
"lgTitleOffsetF",
"mpBottomAngleF",
"mpFillDotSizeF",
"mpFillPatterns",
"mpGridMaskMode",
"mpGridSpacingF",
"mpRightMapPosF",
"mpRightWindowF",
"mpTopPointLatF",
"mpTopPointLonF",
"pmAnnoManagers",
"pmLabelBarSide",
"pmLabelBarZone",
"pmLegendWidthF",
"pmTickMarkZone",
"prGraphicStyle",
"sfElementNodes",
"sfXCActualEndF",
"sfXCEndSubsetV",
"sfXCStartIndex",
"sfYCActualEndF",
"sfYCEndSubsetV",
"sfYCStartIndex",
"stArrowLengthF",
"stLevelPalette",
"stLineOpacityF",
"stMapDirection",
"stMaxLevelValF",
"stMinDistanceF",
"stMinLevelValF",
"stZeroFLabelOn",
"tfDoNDCOverlay",
"tfPolyDrawList",
"tiMainFuncCode",
"tiMainOffsetXF",
"tiMainOffsetYF",
"tiMainPosition",
"tmXBDataRightF",
"tmXBTickStartF",
"tmXTDataRightF",
"tmXTTickStartF",
"tmYLTickStartF",
"tmYRTickStartF",
"trXCoordPoints",
"trXInterPoints",
"trYCoordPoints",
"trYInterPoints",
"txFontOpacityF",
"vcFillArrowsOn",
"vcFillOverEdge",
"vcLevelPalette",
"vcMapDirection",
"vcMaxLevelValF",
"vcMinDistanceF",
"vcMinLevelValF",
"vcPositionMode",
"vcZeroFLabelOn",
"vfXCActualEndF",
"vfXCEndSubsetV",
"vfXCStartIndex",
"vfYCActualEndF",
"vfYCEndSubsetV",
"vfYCStartIndex",
"wkDeviceLowerX",
"wkDeviceLowerY",
"wkDeviceUpperX",
"wkDeviceUpperY",
"wkPSResolution",
"wkPaperHeightF",
"xyDashPatterns",
"xyMarkLineMode",
"xyMarkerColors",
"xyXIrrTensionF",
"xyYIrrTensionF"),14,1);


() = define_keywords_n ($1, strcat( 
"cnConpackParams",
"cnConstFLabelOn",
"cnFillDrawOrder",
"cnHighLabelFont",
"cnInfoLabelFont",
"cnInfoLabelJust",
"cnInfoLabelSide",
"cnInfoLabelZone",
"cnLevelSpacingF",
"cnLineDrawOrder",
"cnLineLabelFont",
"cnLowLabelCount",
"cnMaxLevelCount",
"cnMonoFillColor",
"cnMonoFillScale",
"cnMonoLevelFlag",
"cnMonoLineColor",
"cnNoDataLabelOn",
"ctXTableLengths",
"ctYTableLengths",
"gsLineLabelFont",
"gsTextDirection",
"gsnCenterString",
"gsnPanelRowSpec",
"gsnSpreadColors",
"gsnXYFillColors",
"lbBottomMarginF",
"lbJustification",
"lbLabelFuncCode",
"lbLabelPosition",
"lbMonoFillColor",
"lbMonoFillScale",
"lbTitleFuncCode",
"lbTitlePosition",
"lgBottomMarginF",
"lgBoxBackground",
"lgItemPlacement",
"lgItemPositions",
"lgJustification",
"lgLabelFuncCode",
"lgLabelPosition",
"lgLineLabelFont",
"lgMarkerIndexes",
"lgMonoDashIndex",
"lgMonoLineColor",
"lgTitleFuncCode",
"lgTitlePosition",
"mpAreaMaskingOn",
"mpBottomMapPosF",
"mpBottomWindowF",
"mpFillDrawOrder",
"mpGridAndLimbOn",
"mpGridLineColor",
"mpLandFillColor",
"mpLeftPointLatF",
"mpLeftPointLonF",
"mpLimbLineColor",
"mpMonoFillColor",
"mpMonoFillScale",
"pmLegendHeightF",
"sfMissingValueV",
"stLevelSpacingF",
"stMaxLevelCount",
"stMonoLineColor",
"stNoDataLabelOn",
"tfPlotManagerOn",
"tfPolyDrawOrder",
"tiMainDirection",
"tiMainFontColor",
"tiXAxisFuncCode",
"tiXAxisOffsetXF",
"tiXAxisOffsetYF",
"tiXAxisPosition",
"tiYAxisFuncCode",
"tiYAxisOffsetXF",
"tiYAxisOffsetYF",
"tiYAxisPosition",
"tmSciNoteCutoff",
"tmXBIrrTensionF",
"tmXBLabelAngleF",
"tmXBLabelDeltaF",
"tmXBLabelStride",
"tmXBMinorValues",
"tmXTIrrTensionF",
"tmXTLabelAngleF",
"tmXTLabelDeltaF",
"tmXTLabelStride",
"tmXTMinorValues",
"tmYLDataBottomF",
"tmYLIrrTensionF",
"tmYLLabelAngleF",
"tmYLLabelDeltaF",
"tmYLLabelStride",
"tmYLMinorValues",
"tmYRDataBottomF",
"tmYRIrrTensionF",
"tmYRLabelAngleF",
"tmYRLabelDeltaF",
"tmYRLabelStride",
"tmYRMinorValues",
"vcGlyphOpacityF",
"vcLevelSpacingF",
"vcMaxLevelCount",
"vcMaxMagnitudeF",
"vcMinAnnoAngleF",
"vcMinAnnoString",
"vcMinMagnitudeF",
"vcNoDataLabelOn",
"vcRefAnnoAngleF",
"vcRefAnnoString",
"vcRefMagnitudeF",
"vcUseRefAnnoRes",
"vcWindBarbColor",
"vpAnnoManagerId",
"wkPDFResolution",
"wkTopLevelViews",
"wsThresholdSize",
"xyCoordDataSpec",
"xyLineLabelFont",
"xyMarkLineModes",
"xyMonoLineColor"),15,1);


() = define_keywords_n ($1, strcat( 
"amOrthogonalPosF",
"appDefaultParent",
"cnHighLabelCount",
"cnLabelDrawOrder",
"cnLineLabelCount",
"cnLineThicknessF",
"cnLowLabelAngleF",
"cnLowLabelFormat",
"cnLowLabelString",
"cnOutputFileName",
"gsEdgeThicknessF",
"gsFontThicknessF",
"gsLineThicknessF",
"gsMarkerOpacityF",
"gsnPanelLabelBar",
"gsnScalarContour",
"gsnXRefLineColor",
"gsnYRefLineColor",
"lbFillBackground",
"lbLabelAlignment",
"lbLabelDirection",
"lbLabelFontColor",
"lbPerimFillColor",
"lbTitleDirection",
"lbTitleFontColor",
"lgLabelAlignment",
"lgLabelDirection",
"lgLabelFontColor",
"lgLineThicknessF",
"lgMonoMarkerSize",
"lgPerimFillColor",
"lgTitleDirection",
"lgTitleFontColor",
"mpAreaGroupCount",
"mpDataResolution",
"mpLabelDrawOrder",
"mpLabelFontColor",
"mpLandFillScaleF",
"mpLeftCornerLatF",
"mpLeftCornerLonF",
"mpOceanFillColor",
"mpPerimDrawOrder",
"mpPerimLineColor",
"mpRightPointLatF",
"mpRightPointLonF",
"mpSatelliteDistF",
"pmLabelBarWidthF",
"sfFirstNodeIndex",
"sfXCActualStartF",
"sfXCStartSubsetV",
"sfYCActualStartF",
"sfYCStartSubsetV",
"stLineThicknessF",
"stMinStepFactorF",
"stUseScalarArray",
"stZeroFLabelFont",
"stZeroFLabelJust",
"stZeroFLabelSide",
"stZeroFLabelZone",
"tiXAxisDirection",
"tiXAxisFontColor",
"tiYAxisDirection",
"tiYAxisFontColor",
"tmXBMajorLengthF",
"tmXBMaxLabelLenF",
"tmXBMinorLengthF",
"tmXBTickSpacingF",
"tmXTMajorLengthF",
"tmXTMaxLabelLenF",
"tmXTMinorLengthF",
"tmXTTickSpacingF",
"tmYLMajorLengthF",
"tmYLMaxLabelLenF",
"tmYLMinorLengthF",
"tmYLTickSpacingF",
"tmYRMajorLengthF",
"tmYRMaxLabelLenF",
"tmYRMinorLengthF",
"tmYRTickSpacingF",
"txFontThicknessF",
"vcLabelFontColor",
"vcLineArrowColor",
"vcMinAnnoPerimOn",
"vcMinAnnoString2",
"vcMinFracLengthF",
"vcRefAnnoPerimOn",
"vcRefAnnoString2",
"vcUseScalarArray",
"vcZeroFLabelFont",
"vcZeroFLabelJust",
"vcZeroFLabelSide",
"vcZeroFLabelZone",
"vfExchangeUVData",
"vfMissingUValueV",
"vfMissingVValueV",
"vfXCActualStartF",
"vfXCElementCount",
"vfXCStartSubsetV",
"vfYCActualStartF",
"vfYCElementCount",
"vfYCStartSubsetV",
"wkFullBackground",
"xyCurveDrawOrder",
"xyExplicitLabels",
"xyLineThicknessF",
"xyMonoMarkerSize"),16,1);

() = define_keywords_n ($1, strcat( 
"cnConstFLabelFont",
"cnConstFLabelJust",
"cnConstFLabelSide",
"cnConstFLabelZone",
"cnHighLabelAngleF",
"cnHighLabelFormat",
"cnHighLabelString",
"cnInfoLabelAngleF",
"cnInfoLabelFormat",
"cnInfoLabelString",
"cnLineDashPattern",
"cnLineDashSegLenF",
"cnLineLabelAngleF",
"cnLineLabelFormat",
"cnLineThicknesses",
"cnLowLabelPerimOn",
"cnMonoFillPattern",
"cnRasterCellSizeF",
"cnScalarFieldData",
"cnSpanFillPalette",
"cnSpanLinePalette",
"gsEdgeDashPattern",
"gsEdgeDashSegLenF",
"gsLineDashPattern",
"gsLineDashSegLenF",
"gsLineLabelString",
"gsnAttachBorderOn",
"gsnPolarLabelFont",
"gsnSpreadColorEnd",
"gsnYRefLineColors",
"gsnZonalMeanXMaxF",
"gsnZonalMeanXMinF",
"lbBoxMajorExtentF",
"lbBoxMinorExtentF",
"lbLabelAutoStride",
"lbMonoFillPattern",
"lbPerimThicknessF",
"lgBoxMajorExtentF",
"lgBoxMinorExtentF",
"lgLabelAutoStride",
"lgLineDashSegLenF",
"lgLineDashSegLens",
"lgLineThicknesses",
"lgMonoMarkerColor",
"lgMonoMarkerIndex",
"lgPerimThicknessF",
"mpBottomPointLatF",
"mpBottomPointLonF",
"mpCountyLineColor",
"mpDataBaseVersion",
"mpFixedAreaGroups",
"mpGridLatSpacingF",
"mpGridLonSpacingF",
"mpLandFillPattern",
"mpMonoFillPattern",
"mpOceanFillScaleF",
"mpRightCornerLatF",
"mpRightCornerLonF",
"mpSatelliteAngleF",
"pmLabelBarHeightF",
"stLineStartStride",
"stMinLineSpacingF",
"stScalarFieldData",
"stVectorFieldData",
"tiMainFontAspectF",
"tiMainFontHeightF",
"tiMainFontQuality",
"tmBorderLineColor",
"tmEqualizeXYSizes",
"tmLabelAutoStride",
"tmXBAutoPrecision",
"tmXBLabelFuncCode",
"tmXBMinorPerMajor",
"tmXTAutoPrecision",
"tmXTLabelFuncCode",
"tmXTMinorPerMajor",
"tmYLAutoPrecision",
"tmYLLabelFuncCode",
"tmYLMinorPerMajor",
"tmYRAutoPrecision",
"tmYRLabelFuncCode",
"tmYRMinorPerMajor",
"txPerimThicknessF",
"vcFillArrowHeadXF",
"vcFillArrowHeadYF",
"vcFillArrowWidthF",
"vcMagnitudeFormat",
"vcMinAnnoFuncCode",
"vcMinAnnoStringOn",
"vcRefAnnoFuncCode",
"vcRefAnnoStringOn",
"vcScalarFieldData",
"vcVectorDrawOrder",
"vcVectorFieldData",
"wkBackgroundColor",
"wkDashTableLength",
"wkFillTableLength",
"wkForegroundColor",
"xyLineDashSegLenF",
"xyLineThicknesses",
"xyMonoDashPattern",
"xyMonoMarkerColor"),17,1);

() = define_keywords_n ($1, strcat(
"cnGridBoundPerimOn",
"cnHighLabelPerimOn",
"cnInfoLabelPerimOn",
"cnLabelBarEndStyle",
"cnLabelScaleValueF",
"cnLabelScalingMode",
"cnLegendLevelFlags",
"cnLineDashPatterns",
"cnLineLabelPerimOn",
"cnLineLabelStrings",
"cnLowLabelFuncCode",
"gsMarkerThicknessF",
"gsnMajorLatSpacing",
"gsnMajorLonSpacing",
"gsnMinorLatSpacing",
"gsnMinorLonSpacing",
"gsnStringFontColor",
"lbLabelFontAspectF",
"lbLabelFontHeightF",
"lbLabelFontQuality",
"lbMinLabelSpacingF",
"lbPerimDashPattern",
"lbPerimDashSegLenF",
"lbTitleFontAspectF",
"lbTitleFontHeightF",
"lbTitleFontQuality",
"lgLabelFontAspectF",
"lgLabelFontHeightF",
"lgLabelFontQuality",
"lgLineLabelStrings",
"lgMarkerThicknessF",
"lgPerimDashPattern",
"lgPerimDashSegLenF",
"lgTitleFontAspectF",
"lgTitleFontHeightF",
"lgTitleFontQuality",
"mpDefaultFillColor",
"mpFillBoundarySets",
"mpLabelFontHeightF",
"mpLambertMeridianF",
"mpLambertParallelF",
"mpOceanFillPattern",
"mpOutlineDrawOrder",
"mpOutlineMaskingOn",
"mpSatelliteAngle1F",
"mpSatelliteAngle2F",
"mpUSStateLineColor",
"pmLegendKeepAspect",
"pmTitleDisplayMode",
"stLengthCheckCount",
"stMinArrowSpacingF",
"stSpanLevelPalette",
"stZeroFLabelAngleF",
"stZeroFLabelString",
"tiXAxisFontAspectF",
"tiXAxisFontHeightF",
"tiXAxisFontQuality",
"tiYAxisFontAspectF",
"tiYAxisFontHeightF",
"tiYAxisFontQuality",
"tmBorderThicknessF",
"tmXBLabelDirection",
"tmXBLabelFontColor",
"tmXBMajorLineColor",
"tmXBMinorLineColor",
"tmXTLabelDirection",
"tmXTLabelFontColor",
"tmXTMajorLineColor",
"tmXTMinorLineColor",
"tmYLLabelDirection",
"tmYLLabelFontColor",
"tmYLMajorLineColor",
"tmYLMinorLineColor",
"tmYRLabelDirection",
"tmYRLabelFontColor",
"tmYRMajorLineColor",
"tmYRMinorLineColor",
"txConstantSpacingF",
"txPerimDashLengthF",
"txPerimDashPattern",
"vcLabelFontHeightF",
"vcMinAnnoFontColor",
"vcMinAnnoString2On",
"vcRefAnnoFontColor",
"vcRefAnnoString2On",
"vcSpanLevelPalette",
"vcZeroFLabelAngleF",
"vcZeroFLabelString",
"xyMarkerThicknessF",
"xyMonoMarkLineMode",
"xyXIrregularPoints",
"xyYIrregularPoints"),18,1);


() = define_keywords_n ($1, strcat( 
"cnCellFillEdgeColor",
"cnConstFLabelAngleF",
"cnConstFLabelFormat",
"cnConstFLabelString",
"cnHighLabelFuncCode",
"cnInfoLabelFuncCode",
"cnLabelScaleFactorF",
"cnLineLabelDensityF",
"cnLineLabelFuncCode",
"cnLineLabelInterval",
"cnLowLabelFontColor",
"cnMaxPointDistanceF",
"cnMissingValPerimOn",
"cnMonoLineThickness",
"cnNoDataLabelString",
"cnOutOfRangePerimOn",
"cnOutputGriddedData",
"cnRasterSmoothingOn",
"cnSmoothingTensionF",
"gsLineLabelFuncCode",
"gsTextJustification",
"gsnAttachPlotsXAxis",
"gsnHistogramCompare",
"gsnPaperOrientation",
"gsnSpreadColorStart",
"gsnXYBarChartColors",
"gsnXYLeftFillColors",
"lbBoxLineThicknessF",
"lgBoxLineThicknessF",
"lgLineLabelFuncCode",
"lgMarkerThicknesses",
"lgMonoLineThickness",
"mpDefaultFillScaleF",
"mpDynamicAreaGroups",
"mpLambertParallel1F",
"mpLambertParallel2F",
"mpNationalLineColor",
"mpOutlineSpecifiers",
"mpRelativeCenterLat",
"mpRelativeCenterLon",
"pmLegendDisplayMode",
"stNoDataLabelString",
"stZeroFLabelPerimOn",
"tiUseMainAttributes",
"tmXBIrregularPoints",
"tmXBMajorThicknessF",
"tmXBMinorThicknessF",
"tmXTIrregularPoints",
"tmXTMajorThicknessF",
"tmXTMinorThicknessF",
"tmYLIrregularPoints",
"tmYLMajorThicknessF",
"tmYLMinorThicknessF",
"tmYRIrregularPoints",
"tmYRMajorThicknessF",
"tmYRMinorThicknessF",
"vcMinAnnoPerimColor",
"vcMonoWindBarbColor",
"vcNoDataLabelString",
"vcRefAnnoPerimColor",
"vcScalarValueFormat",
"vcZeroFLabelPerimOn",
"wkDefGraphicStyleId",
"wkMarkerTableLength",
"xyLineLabelFuncCode",
"xyMarkerThicknesses",
"xyMonoLineThickness"),19,1);

() = define_keywords_n ($1, strcat(
"cnConstFLabelPerimOn",
"cnGridBoundFillColor",
"cnHighLabelFontColor",
"cnInfoLabelFontColor",
"cnLevelSelectionMode",
"cnLineLabelFontColor",
"cnLowLabelPerimColor",
"cnLowUseHighLabelRes",
"cnMaxDataValueFormat",
"cnRasterMinCellSizeF",
"cnSmoothingDistanceF",
"gsFillLineThicknessF",
"gsLineLabelFontColor",
"gsnHistogramBinWidth",
"gsnPolarLabelSpacing",
"gsnStringFontHeightF",
"gsnXYAboveFillColors",
"gsnXYBarChartColors2",
"gsnXYBelowFillColors",
"gsnXYRightFillColors",
"gsnZonalMeanYRefLine",
"lbBoxLineDashPattern",
"lbBoxLineDashSegLenF",
"lbFillLineThicknessF",
"lgBoxLineDashPattern",
"lgBoxLineDashSegLenF",
"lgLineLabelFontColor",
"lgMonoLineDashSegLen",
"mpDefaultFillPattern",
"mpEllipticalBoundary",
"mpFillAreaSpecifiers",
"mpGreatCircleLinesOn",
"mpGridLineThicknessF",
"mpLimbLineThicknessF",
"mpMaskAreaSpecifiers",
"pmLabelBarKeepAspect",
"pmLegendParallelPosF",
"pmOverlaySequenceIds",
"sfExchangeDimensions",
"stLevelSelectionMode",
"stZeroFLabelFuncCode",
"tiMainFontThicknessF",
"tmXBLabelFontAspectF",
"tmXBLabelFontHeightF",
"tmXBLabelFontQuality",
"tmXBMinLabelSpacingF",
"tmXTLabelFontAspectF",
"tmXTLabelFontHeightF",
"tmXTLabelFontQuality",
"tmXTMinLabelSpacingF",
"tmYLLabelFontAspectF",
"tmYLLabelFontHeightF",
"tmYLLabelFontQuality",
"tmYLMinLabelSpacingF",
"tmYRLabelFontAspectF",
"tmYRLabelFontHeightF",
"tmYRLabelFontQuality",
"tmYRMinLabelSpacingF",
"vcFillArrowEdgeColor",
"vcFillArrowFillColor",
"vcLevelSelectionMode",
"vcMinAnnoArrowAngleF",
"vcMinAnnoArrowSpaceF",
"vcMinAnnoFontAspectF",
"vcMinAnnoFontHeightF",
"vcMinAnnoFontQuality",
"vcMinAnnoOrientation",
"vcMinAnnoPerimSpaceF",
"vcMonoLineArrowColor",
"vcRefAnnoArrowAngleF",
"vcRefAnnoArrowSpaceF",
"vcRefAnnoFontAspectF",
"vcRefAnnoFontHeightF",
"vcRefAnnoFontQuality",
"vcRefAnnoOrientation",
"vcRefAnnoPerimSpaceF",
"vcWindBarbTickAngleF",
"vcZeroFLabelFuncCode",
"vfExchangeDimensions",
"vfSingleMissingValue",
"xyLineLabelFontColor"),20,1);


() = define_keywords_n ($1, strcat( 
"cnConstFLabelFuncCode",
"cnFillBackgroundColor",
"cnGridBoundFillScaleF",
"cnGridBoundPerimColor",
"cnHighLabelPerimColor",
"cnHighUseLineLabelRes",
"cnInfoLabelPerimColor",
"cnLabelBarEndLabelsOn",
"cnLineLabelFontColors",
"cnLineLabelPerimColor",
"cnLowLabelFontAspectF",
"cnLowLabelFontHeightF",
"cnLowLabelFontQuality",
"cnLowLabelPerimSpaceF",
"cnMissingValFillColor",
"cnMonoLineDashPattern",
"cnOutOfRangeFillColor",
"cnRasterSampleFactorF",
"gsFillBackgroundColor",
"gsnAboveYRefLineColor",
"gsnBelowYRefLineColor",
"gsnDebugWriteFileName",
"gsnPanelFigureStrings",
"gsnPolarLabelDistance",
"gsnXAxisIrregular2Log",
"gsnXRefLineThicknessF",
"gsnXYBarChartBarWidth",
"gsnXYBarChartPatterns",
"gsnYAxisIrregular2Log",
"gsnYRefLineThicknessF",
"lbLabelFontThicknessF",
"lbTitleFontThicknessF",
"lgLabelFontThicknessF",
"lgLineLabelFontColors",
"lgMonoMarkerThickness",
"lgTitleFontThicknessF",
"mpGridLineDashPattern",
"mpGridLineDashSegLenF",
"mpLimbLineDashPattern",
"mpLimbLineDashSegLenF",
"mpOutlineBoundarySets",
"mpPerimLineThicknessF",
"mpSpecifiedFillColors",
"mpSpecifiedFillScales",
"pmLabelBarDisplayMode",
"pmTickMarkDisplayMode",
"stCrossoverCheckCount",
"stLabelBarEndLabelsOn",
"stStreamlineDrawOrder",
"stZeroFLabelFontColor",
"tiXAxisFontThicknessF",
"tiYAxisFontThicknessF",
"tmXMajorGridLineColor",
"tmXMinorGridLineColor",
"tmYMajorGridLineColor",
"tmYMinorGridLineColor",
"trLineInterpolationOn",
"txBackgroundFillColor",
"vcLabelBarEndLabelsOn",
"vcLineArrowThicknessF",
"vcMinAnnoParallelPosF",
"vcRefAnnoParallelPosF",
"vcWindBarbTickLengthF",
"vcZeroFLabelFontColor",
"xyLineLabelFontColors",
"xyMonoMarkerThickness"),21,1);


				    
() = define_keywords_n ($1, strcat( 
"cnConstFLabelFontColor",
"cnExplicitLineLabelsOn",
"cnGridBoundFillPattern",
"cnHighLabelFontAspectF",
"cnHighLabelFontHeightF",
"cnHighLabelFontQuality",
"cnHighLabelPerimSpaceF",
"cnInfoLabelFontAspectF",
"cnInfoLabelFontHeightF",
"cnInfoLabelFontQuality",
"cnInfoLabelPerimSpaceF",
"cnLineLabelFontAspectF",
"cnLineLabelFontHeightF",
"cnLineLabelFontQuality",
"cnLineLabelPerimSpaceF",
"cnMissingValFillScaleF",
"cnMissingValPerimColor",
"cnOutOfRangeFillScaleF",
"cnOutOfRangePerimColor",
"gsLineLabelFontAspectF",
"gsLineLabelFontHeightF",
"gsLineLabelFontQuality",
"gsTextConstantSpacingF",
"gsnHistogramBinMissing",
"gsnHistogramHorizontal",
"gsnLeftStringFontColor",
"gsnPanelScalePlotIndex",
"gsnXRefLineDashPattern",
"gsnXYBarChartPatterns2",
"gsnYRefLineDashPattern",
"gsnYRefLineThicknesses",
"lgLineLabelFontAspectF",
"lgLineLabelFontHeightF",
"lgLineLabelFontHeights",
"lgLineLabelFontQuality",
"mpCountyLineThicknessF",
"mpGeophysicalLineColor",
"mpGridAndLimbDrawOrder",
"mpGridPolarLonSpacingF",
"mpInlandWaterFillColor",
"mpPerimLineDashPattern",
"mpPerimLineDashSegLenF",
"pmLabelBarParallelPosF",
"pmLegendOrthogonalPosF",
"stZeroFLabelPerimColor",
"tiMainConstantSpacingF",
"tmXMajorGridThicknessF",
"tmXMinorGridThicknessF",
"tmYMajorGridThicknessF",
"tmYMinorGridThicknessF",
"vcLabelsUseVectorColor",
"vcMagnitudeScaleValueF",
"vcMagnitudeScalingMode",
"vcMinAnnoTextDirection",
"vcRefAnnoTextDirection",
"vcWindBarbScaleFactorF",
"vcWindBarbTickSpacingF",
"vcZeroFLabelPerimColor",
"xyExplicitLegendLabels",
"xyLineLabelFontAspectF",
"xyLineLabelFontHeightF",
"xyLineLabelFontQuality"),22,1);


() = define_keywords_n ($1, strcat( 
"cnConstFLabelPerimColor",
"cnConstFUseInfoLabelRes",
"cnInfoLabelParallelPosF",
"cnMissingValFillPattern",
"cnOutOfRangeFillPattern",
"gsnHistogramPercentSign",
"gsnMaskLambertConformal",
"gsnRightStringFontColor",
"gsnXYBarChartFillScaleF",
"gsnYRefLineDashPatterns",
"lbLabelConstantSpacingF",
"lbTitleConstantSpacingF",
"lgLabelConstantSpacingF",
"lgTitleConstantSpacingF",
"mpCountyLineDashPattern",
"mpCountyLineDashSegLenF",
"mpFillPatternBackground",
"mpInlandWaterFillScaleF",
"mpMaskOutlineSpecifiers",
"mpSpecifiedFillPatterns",
"mpSpecifiedFillPriority",
"mpUSStateLineThicknessF",
"stScalarMissingValColor",
"stZeroFLabelFontAspectF",
"stZeroFLabelFontHeightF",
"stZeroFLabelFontQuality",
"stZeroFLabelPerimSpaceF",
"tiXAxisConstantSpacingF",
"tiYAxisConstantSpacingF",
"tmXBLabelFontThicknessF",
"tmXBMajorOutwardLengthF",
"tmXBMinorOutwardLengthF",
"tmXTLabelFontThicknessF",
"tmXTMajorOutwardLengthF",
"tmXTMinorOutwardLengthF",
"tmYLLabelFontThicknessF",
"tmYLMajorOutwardLengthF",
"tmYLMinorOutwardLengthF",
"tmYRLabelFontThicknessF",
"tmYRMajorOutwardLengthF",
"tmYRMinorOutwardLengthF",
"vcLineArrowHeadMaxSizeF",
"vcLineArrowHeadMinSizeF",
"vcMagnitudeScaleFactorF",
"vcMinAnnoArrowEdgeColor",
"vcMinAnnoArrowFillColor",
"vcMinAnnoArrowLineColor",
"vcMinAnnoFontThicknessF",
"vcMinAnnoOrthogonalPosF",
"vcRefAnnoArrowEdgeColor",
"vcRefAnnoArrowFillColor",
"vcRefAnnoArrowLineColor",
"vcRefAnnoFontThicknessF",
"vcRefAnnoOrthogonalPosF",
"vcScalarMissingValColor",
"vcZeroFLabelFontAspectF",
"vcZeroFLabelFontHeightF",
"vcZeroFLabelFontQuality",
"vcZeroFLabelPerimSpaceF"),23,1);


() = define_keywords_n ($1, strcat( 
"cnConstFLabelFontAspectF",
"cnConstFLabelFontHeightF",
"cnConstFLabelFontQuality",
"cnConstFLabelPerimSpaceF",
"cnExplicitLegendLabelsOn",
"cnInfoLabelTextDirection",
"cnLineLabelPlacementMode",
"cnLowLabelFontThicknessF",
"cnMonoLineLabelFontColor",
"gsnCenterStringFontColor",
"gsnHistogramBinIntervals",
"gsnHistogramMinMaxBinsOn",
"gsnHistogramNumberOfBins",
"gsnLeftStringFontHeightF",
"gsnPolarLabelFontHeightF",
"gsnXAxisIrregular2Linear",
"gsnXYBarChartOutlineOnly",
"gsnYAxisIrregular2Linear",
"lgMonoLineLabelFontColor",
"mpInlandWaterFillPattern",
"mpNationalLineThicknessF",
"mpUSStateLineDashPattern",
"mpUSStateLineDashSegLenF",
"pmLabelBarOrthogonalPosF",
"stZeroFLabelParallelPosF",
"vcFillArrowHeadMinFracXF",
"vcFillArrowHeadMinFracYF",
"vcFillArrowMinFracWidthF",
"vcMinAnnoArrowMinOffsetF",
"vcMinAnnoBackgroundColor",
"vcMinAnnoPerimThicknessF",
"vcMonoFillArrowEdgeColor",
"vcMonoFillArrowFillColor",
"vcRefAnnoArrowMinOffsetF",
"vcRefAnnoBackgroundColor",
"vcRefAnnoPerimThicknessF",
"vcScalarValueScaleValueF",
"vcScalarValueScalingMode",
"vcWindBarbLineThicknessF",
"vcZeroFLabelParallelPosF",
"xyMonoLineLabelFontColor"),24,1);


() = define_keywords_n ($1, strcat( 
"cnConstFLabelParallelPosF",
"cnHighLabelFontThicknessF",
"cnHighLowLabelOverlapMode",
"cnInfoLabelFontThicknessF",
"cnInfoLabelOrthogonalPosF",
"cnLineLabelFontThicknessF",
"cnLowLabelBackgroundColor",
"cnLowLabelPerimThicknessF",
"gsLineLabelFontThicknessF",
"gsnAboveYRefLineBarColors",
"gsnBelowYRefLineBarColors",
"gsnLeftStringParallelPosF",
"gsnRightStringFontHeightF",
"gsnXYBarChartFillDotSizeF",
"lgLineLabelFontThicknessF",
"lgMonoLineLabelFontHeight",
"mpNationalLineDashPattern",
"mpNationalLineDashSegLenF",
"stZeroFLabelTextDirection",
"tmXBLabelConstantSpacingF",
"tmXTLabelConstantSpacingF",
"tmYLLabelConstantSpacingF",
"tmYRLabelConstantSpacingF",
"vcFillArrowEdgeThicknessF",
"vcFillArrowHeadInteriorXF",
"vcMinAnnoArrowUseVecColor",
"vcMinAnnoConstantSpacingF",
"vcRefAnnoArrowUseVecColor",
"vcRefAnnoConstantSpacingF",
"vcScalarValueScaleFactorF",
"vcWindBarbCalmCircleSizeF",
"vcZeroFLabelTextDirection",
"xyLineLabelFontThicknessF"),25,1);


() = define_keywords_n ($1, strcat( 
"cnConstFLabelTextDirection",
"cnExplicitLabelBarLabelsOn",
"cnGridBoundPerimThicknessF",
"cnHighLabelBackgroundColor",
"cnHighLabelPerimThicknessF",
"cnInfoLabelBackgroundColor",
"cnInfoLabelPerimThicknessF",
"cnLineLabelBackgroundColor",
"cnLineLabelPerimThicknessF",
"cnLowLabelConstantSpacingF",
"gsnCenterStringFontHeightF",
"gsnHistogramClassIntervals",
"gsnPanelXWhiteSpacePercent",
"gsnPanelYWhiteSpacePercent",
"gsnRightStringParallelPosF",
"stExplicitLabelBarLabelsOn",
"stZeroFLabelFontThicknessF",
"stZeroFLabelOrthogonalPosF",
"vcExplicitLabelBarLabelsOn",
"vcZeroFLabelFontThicknessF",
"vcZeroFLabelOrthogonalPosF"),26,1);

() = define_keywords_n ($1, strcat( 
"cnConstFLabelFontThicknessF",
"cnConstFLabelOrthogonalPosF",
"cnGridBoundPerimDashPattern",
"cnHighLabelConstantSpacingF",
"cnInfoLabelConstantSpacingF",
"cnLineLabelConstantSpacingF",
"cnMissingValPerimThicknessF",
"cnOutOfRangePerimThicknessF",
"gsLineLabelConstantSpacingF",
"gsnAboveYRefLineBarPatterns",
"gsnBelowYRefLineBarPatterns",
"gsnCenterStringParallelPosF",
"gsnHistogramBarWidthPercent",
"gsnLeftStringOrthogonalPosF",
"lgLineLabelConstantSpacingF",
"mpGeophysicalLineThicknessF",
"stZeroFLabelBackgroundColor",
"stZeroFLabelPerimThicknessF",
"tmXMajorGridLineDashPattern",
"tmXMinorGridLineDashPattern",
"tmYMajorGridLineDashPattern",
"tmYMinorGridLineDashPattern",
"vcMinAnnoExplicitMagnitudeF",
"vcRefAnnoExplicitMagnitudeF",
"vcZeroFLabelBackgroundColor",
"vcZeroFLabelPerimThicknessF",
"xyLineLabelConstantSpacingF"),27,1);


() = define_keywords_n ($1, strcat( 
"cnConstFLabelBackgroundColor",
"cnConstFLabelPerimThicknessF",
"cnMissingValPerimDashPattern",
"cnMissingValPerimGridBoundOn",
"cnOutOfRangePerimDashPattern",
"gsnContourNegLineDashPattern",
"gsnContourPosLineDashPattern",
"gsnContourZeroLineThicknessF",
"gsnPanelFigureStringsPerimOn",
"gsnRightStringOrthogonalPosF",
"mpGeophysicalLineDashPattern",
"mpGeophysicalLineDashSegLenF",
"stZeroFLabelConstantSpacingF",
"vcZeroFLabelConstantSpacingF"),28,1);

() = define_keywords_n ($1,  strcat ("cnCellFillMissingValEdgeColor",
"cnConstFLabelConstantSpacingF",
"gsnAboveYRefLineBarFillScales",
"gsnBelowYRefLineBarFillScales",
"gsnCenterStringOrthogonalPosF",
"gsnHistogramDiscreteBinValues",
"mpSpecifiedFillDirectIndexing"),29,1);
	 
() = define_keywords_n ($1,  strcat ("gsnContourLineThicknessesScale",
			     "gsnHistogramComputePercentages",
                             "gsnXYBarChartOutlineThicknessF"), 30,1);

() = define_keywords_n ($1,  strcat ("gsnHistogramDiscreteClassValues",
			     "gsnHistogramSelectNiceIntervals",
			     "gsnXYBarChartFillLineThicknessF"), 31, 1);

() = define_keywords_n ($1, "gsnMaskLambertConformalOutlineOngsnPanelFigureStringsFontHeightF", 32,1);

%%'gsnPanelFigureStringsBackgroundFillColor'

() = define_keywords_n ($1,  "gsnHistogramComputePercentagesNoMissing", 39,1);

() = define_keywords_n ($1, "gsnPanelFigureStringsBackgroundFillColor", 40,1);

%%%%%%%%%%%%%%%55

%%% table 2 is reserved words aka keywords and for variable type
%%% declarations
%% these are options to resources and assigned to highlight table 2
%% the above were added to this table because table number too high
%% error when trying to use table 3
() = define_keywords_n ($1, "doif",2,2);


() = define_keywords_n ($1, strcat(
"App",
"Log",
"Low",
"Map",
"NDC",
"NPC",
"Nhl",
"Top",
"end",
"new"), 3, 2);
 
() = define_keywords_n ($1, strcat(
"Down",
"Draw",
"Fine",
"High",
"Left",
"NULL",
"QUIT",
"Quit",
"TRUE",
"Time",
"True",
"byte",
"char",
"else",
"enum",
"file",
"list",
"load",
"long",
"quit",
"stop",
"then",
"uint",
"vlen" ), 4, 2);

() = define_keywords_n ($1, strcat(
"FALSE",
"False",
"Lines",
"Never",
"RANGS",
"Right",
"Solid",
"begin",
"break",
"float",
"group",
"int64",
"local",
"short",
"ubyte",
"ulong",
"while"), 5, 2);
 
() = define_keywords_n ($1, strcat(
"Across",
"Always",
"Angles",
"Bottom",
"Center",
"Coarse",
"Custom",
"Finest",
"Footer",
"LatLon",
"Linear",
"LogLin",
"LowRes",
"Manual",
"Medium",
"NoLine",
"Points",
"Window",
"XyPlot",
"create",
"double",
"opaque",
"pwritx",
"record",
"return",
"stdout",
"string",
"uint64",
"ushort",
"xtable",
"ytable"), 6, 2);
 
 
() = define_keywords_n ($1, strcat(
"Corners",
"HighRes",
"LogAxis",
"Markers",
"Missing",
"Polygon",
"PreDraw",
"TimePos",
"TopLeft",
"graphic",
"integer",
"logical",
"numeric" ), 7, 2);
 
() = define_keywords_n ($1, strcat(
"AdjustVP",
"AreaFill",
"CellFill",
"Coarsest",
"Computed",
"Constant",
"Explicit",
"Gnomonic",
"InitTime",
"LabelBar",
"Lettered",
"LineOnly",
"MaskLand",
"MaskNone",
"Mercator",
"National",
"Ncarg4_0",
"NoCreate",
"NoLabels",
"NoTitles",
"NullArea",
"NullFill",
"Polyline",
"PostDraw",
"Robinson",
"TopRight",
"USStates",
"Vertical",
"ViewPort",
"WindBarb",
"_Missing",
"appClass",
"compound",
"continue",
"enumeric",
"external",
"function",
"noparent",
"objClass",
"snumeric"), 8, 2);
 
 
() = define_keywords_n ($1, strcat(
"ArrowHead",
"ArrowTail",
"Automatic",
"FillArrow",
"Irregular",
"LabelOnly",
"LineArrow",
"MainTitle",
"MarkLines",
"MaskOcean",
"MediumRes",
"Mollweide",
"NullColor",
"NullObjId",
"Satellite",
"SolidFill",
"SolidLine",
"Solidline",
"Spherical",
"TimeLabel",
"TopCenter",
"TrimZeros",
"UnitLabel",
"ValidTime",
"baseClass",
"character",
"getvalues",
"procedure",
"setvalues",
"viewClass"), 9, 2);
 
() = define_keywords_n ($1, strcat(
"AboveBoxes",
"AboveItems",
"Background",
"BelowBoxes",
"BelowItems",
"BottomLeft",
"BoxCenters",
"CenterLeft",
"FieldTitle",
"FixedGrids",
"Foreground",
"FreeAspect",
"Geographic",
"HollowFill",
"Horizontal",
"LinearAxis",
"NumVectors",
"OmitOverHL",
"OmitOverVP",
"Polymarker",
"Randomized",
"RasterFill",
"VectorPlot",
"_FillValue",
"defaultapp",
"errorClass",
"styleClass",
"titleClass"), 10, 2);
 
() = define_keywords_n ($1, strcat(
"AllIntegers",
"ArrowCenter",
"BottomRight",
"CenterRight",
"CommonTitle",
"Conditional",
"ContourPlot",
"CoordArrays",
"CurlyVector",
"Curvilinear",
"Geophysical",
"ItemCenters",
"MaskNotLand",
"MaximalArea",
"NDCViewport",
"PlotLevelID",
"PlotManager",
"RANGS_GSHHS",
"ScalarField",
"ScaleFactor",
"Transparent",
"Unspecified",
"VectorField",
"legendClass",
"xyPlotClass"), 11, 2);



() = define_keywords_n ($1, strcat(
"BottomCenter",
"CenterCenter",
"LineAndLabel",
"MainTitlePos",
"ManualLevels",
"MaskFillArea",
"MaskMaskArea",
"MaskNotOcean",
"NhlTPosition",
"NoBoundaries",
"Orthographic",
"SingleVector",
"SplitVectors",
"mapPlotClass"), 12, 2);
 
() = define_keywords_n ($1, strcat(
"AllBoundaries",
"DataTransform",
"ExternalEdges",
"GaussianGrids",
"IgnoreOverlap",
"InteriorEdges",
"IrregularAxis",
"NDCDataExtent",
"NhlBACKGROUND",
"NhlFOREGROUND",
"Stereographic",
"UniformSizing",
"dataCommClass",
"dataItemClass",
"dataSpecClass",
"labelBarClass",
"mpContinental",
"mpGeophysical",
"textItemClass",
"tickMarkClass"), 13, 2);
 
() = define_keywords_n ($1, strcat(
"ConfineToRange",
"ExplicitLevels",
"ExplicitSizing",
"FineResolution",
"NhlDEFAULT_APP",
"NhlTRANSPARENT",
"NoHeaderFooter",
"StreamlinePlot",
"TriangularMesh",
"primitiveClass",
"transformClass",
"workspaceClass",
"xtable_lengths",
"ytable_lengths"), 14, 2);
 
() = define_keywords_n ($1, strcat(
"AutomaticLevels",
"MultipleVectors",
"OmitOverVPAndHL",
"RotatedMercator",
"logLinPlotClass",
"vectorPlotClass",
"xyDataSpecClass"), 15, 2);
 
() = define_keywords_n ($1, strcat(
"CoarseResolution",
"FinestResolution",
"FixedAspectFitBB",
"FixedOffsetGrids",
"LambertConformal",
"LambertEqualArea",
"MaxSigDigitsLeft",
"MediumResolution",
"UniformPlacement",
"annoManagerClass",
"contourPlotClass",
"coordArraysClass",
"plotManagerClass",
"scalarFieldClass",
"vectorFieldClass",
"workstationClass"), 16, 2);

() = define_keywords_n ($1, strcat(
"ContourParameters",
"EqualSpacedLevels",
"ExcludeOuterBoxes",
"ExplicitPlacement",
"IncludeOuterBoxes",
"NhlTTextDirection",
"PoliticalPriority",
"graphicStyleClass",
"xWorkstationClass"), 17, 2);
 
() = define_keywords_n ($1, strcat(
"AdjustVPOmitOverHL",
"CoarsestResolution",
"FixedAspectNoFitBB",
"coordArrTableClass",
"irregularPlotClass",
"psWorkstationClass"), 18, 2);
 
() = define_keywords_n ($1, strcat(
"GeophysicalPriority",
"IncludeMinMaxLabels",
"NhlLAMBERTCONFORMAL",
"pdfWorkstationClass",
"streamlinePlotClass",
"transformationClass"), 19, 2);

() = define_keywords_n ($1, strcat(
"AzimuthalEquidistant",
"CylindricalEqualArea",
"meshScalarFieldClass",
"ncgmWorkstationClass"), 20, 2);
 
() = define_keywords_n ($1, strcat(
"UnspecifiedResolution",
"imageWorkstationClass" ), 21, 2);

() = define_keywords_n ($1, strcat(
"CylindricalEquidistant"), 22,2);

() = define_keywords_n ($1, strcat(
"documentWorkstationClass"), 24 ,2); 

() = define_keywords_n ($1, strcat(
"logLinTransformationClass"), 25, 2); 


() = define_keywords_n ($1, strcat(
"irregularTransformationClass",
"sphericalTransformationClass"), 28, 2);


() = define_keywords_n ($1, strcat(
"curvilinearTransformationClass"),30,2);


() = define_keywords_n ($1, strcat(
"triangularMeshTransformationClass"),33,2);

() = define_keywords_n ($1, strcat(
"GeophysicalAndUSStates",
"mapTransformationClass"), 22, 2);

() = define_keywords_n ($1, 
"documentWorkstationClass",24 ,2); 

() = define_keywords_n ($1, 
"logLinTransformationClass",25,2); 


() = define_keywords_n ($1, strcat(
"irregularTransformationClass",
"sphericalTransformationClass"),28,2);


() = define_keywords_n ($1, 
"curvilinearTransformationClass",30,2);


() = define_keywords_n ($1, strcat(
"triangularMeshTransformationClass"),33,2);


define ncl_mode ()
{
   
   set_mode("ncl", 0);
   use_syntax_table ("NCL");
   run_mode_hooks ("ncl_mode_hook");
   set_fortran_comment_chars("NCL", ";");
   %% set default colors  change to your desires
   set_color("normal", "black", "brightwhite");
   set_color ("cursor", "brightwhite", "blue");
   set_color("dollar", "brightred", "brightwhite");
   set_color("...", "red", "white");    			  % folding indicator  does this work?? tjo
   set_color("operator", "red", "brightwhite");      % +, -, etc..
   set_color("number", "brightblue", "brightwhite");    % 10, 2.71, etc..
   set_color("comment", "black", "lightcyan");% /* comment */
   set_color("region", "yellow", "brightmagenta");
   set_color("string", "blue", "brightwhite");    % "string" or 'char'
   set_color("keyword", "red", "brightwhite");    % if, while,... reserved words and functions
   set_color("keyword1", "darkgreen", "brightwhite");    % if, while, unsigned, ... resources
   set_color("keyword2", "red", "white"); %%ncl reserved words anything else
   set_color("keyword3", "red", "white"); %%ncl reserved words anything else 
   set_color("delimiter", "darkblue", "brightwhite");     % {}[](),.;...
   set_color("trailing_whitespace", "brightwhite", "white");
   set_color("tab", "white", "lightgray");
   set_color("delimiter", "brightred","brightwhite");
   set_color("comma","darkblue","white");
   Highlight_Whitespace = 3; 
}

ncl_mode();

